spring.application.name=gav
#ENTORNO DE PRODUCCION FINAL
#ACTIVACION DEL PERFIL O ENTORNO DEV
spring.profiles.active=dev

#CONEXION A DB MYSQL
spring.datasource.url.url=
spring.datasource.username=
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=


#CONEXION CON POSTGRE DESDE LA NUBE
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


#LOG DE CONEXION PARA PRUEBAS
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG